Repository ironcore-dev/ironcore-dev.github.io, pull requests merged in 2025-06, with the labels that each got.

#39 Define contribution guideline
  CODEOWNERS
  docs/contribute/contributing.md
Labels: documentation, enhancement, size/L

#37 Add documentation style guide
  docs/contribute/style-guide.md
Labels: documentation, enhancement, size/L

#40 Use vitepress rendering
  .github/dependabot.yml
  .github/workflows/publish-docs.yml
  .gitignore
  Makefile
  REUSE.toml
  docs/Dockerfile
  docs/baremetal/architecture/index.md
  docs/baremetal/kubernetes/capi.md
  docs/baremetal/kubernetes/cloud-controller-manager.md
  docs/baremetal/kubernetes/gardener.md
  docs/baremetal/kubernetes/metal-loadbalancer-controller.md
  docs/iaas/architecture/index.md
  docs/iaas/architecture/providers/index.md
  docs/iaas/architecture/runtime-interface.md
  docs/iaas/kubernetes/csi-driver.md
  docs/iaas/kubernetes/gardener.md
  docs/index.md
  docs/overview/index.md
  docs/overview/principles.md
  docs/requirements.txt
  docs/support/index.md
  hack/start-docs.sh
  mkdocs.yml
  package-lock.json
  package.json
Labels: documentation, enhancement, size/XXL

#42 Add API references and other improvements
  docs/.vitepress/config.mts
  docs/iaas/api-references/[group].md
  docs/iaas/api-references/[group].paths.js
  docs/iaas/api-references/index.md
  docs/iaas/architecture/index.md
  docs/iaas/architecture/providers/brokers.md
  docs/index.md
  docs/overview/index.md
  docs/overview/principles.md
Labels: documentation, enhancement, size/L

#43 Add architecture overview section
  docs/iaas/architecture/index.md
  docs/public/architecture-overview.png
Labels: documentation, size/S

#47 Add getting started guide for IaaS
  docs/iaas/getting-started.md
  docs/public/ironcore-in-a-box.png
Labels: documentation, enhancement, size/M

#51 Update IaaS usage guides
  docs/iaas/usage-guides/compute.md
  docs/iaas/usage-guides/core.md
  docs/iaas/usage-guides/networking.md
  docs/iaas/usage-guides/storage.md
Labels: documentation, enhancement, size/M

#52 Add IRI documentation
  docs/iaas/architecture/runtime-interface.md
Labels: documentation, enhancement, size/M

#54 Add Kubernetes overview section
  docs/.vitepress/config.mts
  docs/iaas/kubernetes/index.md
Labels: documentation, enhancement, size/S

#55 Update CSI driver documentation
  docs/iaas/kubernetes/csi-driver.md
Labels: documentation, enhancement, size/M

#57 Add `libvirt-provider` documentation
  docs/.vitepress/config.mts
  docs/iaas/architecture/providers/compute.md
  docs/iaas/architecture/providers/libvirt-provider.md
Labels: documentation, enhancement, size/M

#63 Add metal automation overview and reference docs
  docs/.vitepress/config.mts
  docs/baremetal/api-references/[group].md
  docs/baremetal/api-references/[group].paths.js
  docs/baremetal/api-references/index.md
  docs/baremetal/getting-started.md
  docs/baremetal/index.md
  docs/iaas/architecture/os-images.md
  docs/index.md
  docs/overview/index.md
Labels: documentation, enhancement, size/M

#69 Add BM architecture overview
  docs/baremetal/architecture/index.md
  docs/public/metal-automation-overview.png
Labels: documentation, enhancement, size/S

#70 Add favicon
  docs/.vitepress/config.mts
  docs/public/favicon.ico
Labels: size/XS, chore

#71 Reorganize nav bar
  docs/.vitepress/config.mts
Labels: enhancement, size/XS

#72 Add documentation for `Gardener` Integration with `IronCore`
  docs/baremetal/index.md
  docs/contribute/contributing.md
  docs/iaas/architecture/networking.md
  docs/iaas/kubernetes/cloud-controller-manager.md
  docs/iaas/kubernetes/gardener.md
  docs/iaas/kubernetes/index.md
  docs/iaas/usage-guides/core.md
Labels: documentation, enhancement, size/M

#76 Add docs for BM discovery and first boot
  README.md
  docs/.vitepress/config.mts
  docs/baremetal/architecture/discovery.md
  docs/baremetal/index.md
  docs/public/favicon.ico
Labels: documentation, enhancement, size/L

#79 Add BM provisioning documentation
  docs/baremetal/architecture/discovery.md
  docs/baremetal/architecture/provisioning.md
Labels: documentation, enhancement, size/L

#80 Fix BM provisioning and discovery graphs
  docs/baremetal/architecture/discovery.md
  docs/baremetal/architecture/provisioning.md
Labels: bug, documentation, size/XS

#81 Add documentation for bare metal ccm
  docs/baremetal/kubernetes/cloud-controller-manager.md
  docs/iaas/kubernetes/cloud-controller-manager.md
  docs/iaas/kubernetes/csi-driver.md
Labels: documentation, enhancement, size/L
