Repository ironcore-dev/ironcore-dev.github.io, pull requests merged in 2025-07, with the labels that each got.

#84 Add metal-loadbalancer-controller documentation
  docs/baremetal/kubernetes/metal-loadbalancer-controller.md
Labels: documentation, enhancement, size/S

#85 Add BM gardener documentation
  docs/.vitepress/config.mts
  docs/baremetal/kubernetes/capi.md
  docs/baremetal/kubernetes/gardener.md
Labels: documentation, enhancement, size/M

#87 Add bmwe logo to footer
  docs/.vitepress/config.mts
  docs/public/bmwe.png
Labels: size/S, chore

#92 Fix `ironcore-in-a-box` git url
  docs/iaas/getting-started.md
Labels: bug, documentation, size/XS
